### ISSUE TITLE
Get SS58 prefix from metadata

### ISSUE THREAD

**Issue by arrudagates** [topmonks/calamar#111]
The current implementation of address encoding relies on matching strings representing the name of the chain between 2 different registries by different entities where you can't assume that string will always match, this is not a theoretical issue, it can be seen right now in networks like Tinkernet and GM, where the chain names in the subsquid archive registry are `invarch-tinkernet` and `gmordie`, while in parity's ss58 registry they are `tinker` and `gm`. This is intentional, as there's no requirement that prefix X is exclusively dedicated to chain Y.

The solution is quite simple actually, instead of doing this messy string matching, the ss58 prefix can just be decoded from the metadata present in the subsquid archive, like so:

In `utils/decodeMetadata.ts`:
```typescript
[...]
// Get ss58 prefix from metadata, if for some reason it's undefined we fallback to 42 (generic substrate prefix)
const ss58Format: number = latestMetadata.registry.getChainProperties()?.ss58Format.unwrap()?.toNumber() || 42;
[...]
```

**Comment by uiii** [comment]
Hi @arrudagates, yeah you are right. Our current implementation is wrong, thanks for the tip of a better solution.

**Comment by uiii** [comment]
Hi @arrudagates, I'm working on the fix but found out it returns `42` for `polkadot` and `statemint` instead of `0`, do you know why?

**Comment by arrudagates** [comment]
> Hi @arrudagates, I'm working on the fix but found out it returns `42` for `polkadot` and `statemint` instead of `0`, do you know why? Other chains are fine.
> 
> I know 42 is generic substrate address but not sure why is is stored for these chains in metadata.

This is not an issue with the metadata, it's actually a JavaScript/TypeScript issue. What's happening there is very silly, but it's literally because JavaScript assumes `0` equals `false`, so that expression will always return the correct prefix, except when it's somehow undefined and also when it's 0, because of this bad behavior.
Anyway, here's a solution that works even if the prefix is 0:

```javascript
const maybeSS58Format = latestMetadata.registry.getChainProperties()?.ss58Format.unwrap()?.toNumber();
const ss58Format = typeof maybeSS58Format === "number" ? maybeSS58Format : 42;
```

Instead of asserting on the value coming from the first expression, we assert on the type of the value instead, so even when it's 0, it should be of type "number", the only situation where it would default to 42 would be when it truly can't find a prefix in the registry.

**Comment by uiii** [comment]
Omg, I feel a little embarrased now 😅 Of course I know it works this way but I just overlooked it in my code. I thought I'm defaulting to 42 in different place, but I used your exact code when extracting the value. However thanks for pointing me to the right place 👍
