### ISSUE TITLE
Some account details not working

### ISSUE THREAD

**Issue by uiii** [topmonks/calamar#20]
https://calamar.app/kusama/account/0x565d3c8cd1fcc93ed837d3f9830e333659cd0962ae7fadb7c87899d0b1431822

**Comment by uiii** [comment]
It is because of the query is failing on timeout: https://gist.github.com/uiii/2cd2b8dbbbe9bcecd0ce2ebdbf7a7c93

We must wait to be optimized by subsquid.

**Comment by RostislavLitovkin** [comment]
it works now

**Comment by RostislavLitovkin** [comment]
however this one does not work: https://calamar.app/kusama/account/0x90c6619c6ba60125e49e75e1ea5d9b46431ba834d005319cc036104c94fcfd34
