### ISSUE TITLE
Add related items listings

### ISSUE THREAD

**Issue by uiii** [topmonks/calamar#27]
Add missing related items listing to detail pages

- block's transfers, call and events
- extrinsic's calls

**Comment by arrudagates** [comment]
Don't know if this is the correct issue, but being able to see all transfers (in and out) from the searched account would make my life a whole lot easier!

**Comment by uiii** [comment]
Hi @arrudagates, yes, we have this in our backlog and will implement it in our next milestone.

**Comment by uiii** [comment]
> Currently only the block's transfers are missing.

Should be block's extrinsics, moving transfers to next milestone

**Comment by RostislavLitovkin** [comment]
Thx for clarification. Everything is in place now ^^

**Comment by uiii** [comment]
@arrudagates instead of #62 watch new dedicated issue #99
