### ISSUE TITLE
Show SS58 encoded addresses

### ISSUE THREAD

**Issue by arrudagates** [topmonks/calamar#44]
Instead of showing raw hex addresses, it would be better UX to show the SS58 encoded address for the specific chain being explored.
Perhaps this can be matched against a mapping of squid_name -> ss58_prefix manually kept in this repo, or you could match the name of the chain against a repository of chain info, like Nova's: https://github.com/nova-wallet/nova-utils/blob/master/chains/v5/chains.json

**Comment by uiii** [comment]
Hi, yes, good point, we are going to do it soon. Related to #29

**Comment by uiii** [comment]
I think this is done. Check it please and feel free to reopen if you think it is not implemented as you thought.
